apiVersion: k8s.cni.cncf.io/v1
kind: NetworkAttachmentDefinition
metadata: # kpt-merge: example/cucp-ran-n2
  name: cucp-ran-n2
  namespace: oai-ran-cucp
  annotations:
    internal.kpt.dev/upstream-identifier: k8s.cni.cncf.io|NetworkAttachmentDefinition|example|cucp-ran-n2
spec:
  config: |-
    {
      "cniVersion": "0.3.1",
      "name": "cucp-ran-n2",
      "plugins": [
        {
          "type": "macvlan",
          "capabilities": {
            "ips": true
          },
          "master": "mltus_ens19_110",
          "mode": "bridge",
          "ipam": {
            "type": "static",
            "routes": [
              {
                "dst": "192.168.55.0/24",
                "gw": "192.168.59.1"
              }
            ]
          }
        }
      ]
    }
---
apiVersion: k8s.cni.cncf.io/v1
kind: NetworkAttachmentDefinition
metadata: # kpt-merge: example/cucp-ran-f1c
  name: cucp-ran-f1c
  namespace: oai-ran-cucp
  annotations:
    internal.kpt.dev/upstream-identifier: k8s.cni.cncf.io|NetworkAttachmentDefinition|example|cucp-ran-f1c
spec:
  config: |-
    {
      "cniVersion": "0.3.1",
      "name": "cucp-ran-f1c",
      "plugins": [
        {
          "type": "macvlan",
          "capabilities": {
            "ips": true
          },
          "master": "mltus_ens19_109",
          "mode": "bridge",
          "ipam": {
            "type": "static"
          }
        }
      ]
    }
---
apiVersion: k8s.cni.cncf.io/v1
kind: NetworkAttachmentDefinition
metadata: # kpt-merge: example/cucp-ran-e1
  name: cucp-ran-e1
  namespace: oai-ran-cucp
  annotations:
    internal.kpt.dev/upstream-identifier: k8s.cni.cncf.io|NetworkAttachmentDefinition|example|cucp-ran-e1
spec:
  config: |-
    {
      "cniVersion": "0.3.1",
      "name": "cucp-ran-e1",
      "plugins": [
        {
          "type": "macvlan",
          "capabilities": {
            "ips": true
          },
          "master": "mltus_ens19_108",
          "mode": "bridge",
          "ipam": {
            "type": "static"
          }
        }
      ]
    }
