apiVersion: v1
kind: ConfigMap
metadata: # kpt-merge: frr-k8s-system/frr-init-conf
  name: frr-init-conf
  namespace: frr-k8s-system
  annotations:
    internal.kpt.dev/upstream-identifier: '|ConfigMap|frr-k8s-system|frr-init-conf'
data:
  frr-init.sh: |
    sleep 20
    ip link add dev e1vrf type vrf table 1
    ip link add dev f1vrf type vrf table 2
    ip link add dev n2vrf type vrf table 3
    ip link set dev e1vrf up
    ip link set dev f1vrf up
    ip link set dev n2vrf up
    ip link set dev e1 master e1vrf
    ip link set dev e1uplink master e1vrf
    ip link set dev f1 master f1vrf
    ip link set dev f1uplink master f1vrf
    ip link set dev n2 master n2vrf
    ip link set dev n2uplink master n2vrf
