apiVersion: v1
kind: ConfigMap
metadata: # kpt-merge: frr-k8s-system/vpp-startup-conf
  name: vpp-startup-conf
  namespace: frr-k8s-system
  annotations:
    internal.kpt.dev/upstream-identifier: '|ConfigMap|frr-k8s-system|vpp-startup-conf'
data:
  startup.conf: |
    unix {
      nodaemon
      log /var/log/vpp/vpp.log
      cli-listen /run/vpp/cli.sock
      gid vpp
      poll-sleep-usec 1000
      exec /etc/vpp/bootstrap.vpp
    }

    api-trace { on }
    api-segment { gid vpp }
    socksvr { default }

    memory {
      main-heap-size 512M
      main-heap-page-size default-hugepage
    }

    buffers {
      buffers-per-numa 128000
      default data-size 2048
      page-size default-hugepage
    }

    statseg {
      size 1G
      page-size default-hugepage
      per-node-counters off
    }

    plugins {
      plugin linux_nl_plugin.so { enable }
      plugin linux_cp_plugin.so { enable }
      plugin dpdk_plugin.so { enable }
    }

    logging {
      default-log-level info
      default-syslog-log-level notice
      class linux-cp { rate-limit 10000 level debug syslog-level debug }
      class linux-nl { rate-limit 10000 level debug syslog-level debug }
    }

    dpdk {
     dev 0000:00:14.0 {name dpdk0}
    }
---
apiVersion: v1
kind: ConfigMap
metadata: # kpt-merge: frr-k8s-system/vpp-init-conf
  name: vpp-init-conf
  namespace: frr-k8s-system
  annotations:
    internal.kpt.dev/upstream-identifier: '|ConfigMap|frr-k8s-system|vpp-init-conf'
data:
  bootstrap.vpp: "lcp lcp-sync on\nlcp lcp-auto-subint on\nip table add 1\nip table add 2\nip table add 3              \ncreate sub-interfaces dpdk0 108\ncreate sub-interfaces dpdk0 109\ncreate sub-interfaces dpdk0 110\ncreate sub-interfaces dpdk0 205\ncreate sub-interfaces dpdk0 206\ncreate sub-interfaces dpdk0 207\nset interface ip table dpdk0.108 1\nset interface ip table dpdk0.205 1\nset interface ip table dpdk0.109 2\nset interface ip table dpdk0.206 2\nset interface ip table dpdk0.110 3\nset interface ip table dpdk0.207 3\nset interface state dpdk0 up\nset interface state dpdk0.108 up\nset interface state dpdk0.109 up\nset interface state dpdk0.110 up\nset interface state dpdk0.205 up\nset interface state dpdk0.206 up\nset interface state dpdk0.207 up\nlcp create dpdk0 host-if dpdk0\nlcp create dpdk0.108 host-if e1\nlcp create dpdk0.205 host-if e1uplink\nlcp create dpdk0.109 host-if f1\nlcp create dpdk0.206 host-if f1uplink\nlcp create dpdk0.110 host-if n2\nlcp create dpdk0.207 host-if n2uplink\nset interface ip address dpdk0.108 192.168.57.1/24\nset interface ip address dpdk0.109 192.168.58.1/24\nset interface ip address dpdk0.110 192.168.59.1/24\nset interface ip address dpdk0.205 192.168.60.21/30\nset interface ip address dpdk0.206 192.168.60.25/30\nset interface ip address dpdk0.207 192.168.60.29/30\n"
